{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
name: {{ .Values.secret.name }}
data:
{{- range $key, $value := .Values.secret.data }}
{{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
